### ISSUE TITLE
Alpha not applied after MOUSE event

### ISSUE THREAD

**Issue by Crystallugia** [openfl/swf#25]
(This bug has been filed at the Openfl forum as well)
When I want to apply an alpha to a MovieClip targeting cpp it doesn't do that when the code is in a Mouse Eventlistener. (In an ENTER_FRAME it works as should, but an expensive workaround with a mouseover and an enterframe doesn't work either) When I trace the alpha however it gives me the right value (but not the right visuals). When I set the alpha immediately after the instantiation of the MovieClip the alpha is applied properly. Example:
function init()
{
mc = cast Assets.getMovieClip(“myMovieclip”);
addChild(mc);
mc.addEventListener(MouseEvent.CLICK, click);
}
private function click(e:Event):Void
{
mc.alpha = 0.5;
mc.x+=10;
trace(mc.alpha);
}
While the x value is applied as expected.
Targeting flash all works well, of course.

**Comment by kevinresol** [comment]
I experienced this problem as well. I doubt that some "redraw" event need be triggered.

**Comment by jgranick** [comment]
This works in current versions, thank you :smile:
