### ISSUE TITLE
*html5* Array access is not allowed on format.swf.utils.BitArray, format.swf.SWFData and flash.utils.ByteArray

### ISSUE THREAD

**Issue by redannick** [openfl/swf#37]
Hi, I'm new to openfl but I'm trying to port an old as3/swf project to openfl for html5 output. I've got as far as importing the swf and being able to publish some of it's contents back to a swf target, but when I try to target html5 I'm getting a couple of dozen of these array access errors. Am I just being dumb and missing something? I can't find any other report of this online

thanks!

C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/utils/BitArray.hx:20: characters 18-22 : Array access is not allowed on format.swf.utils.BitArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/utils/BitArray.hx:67: characters 4-8 : Array access is not allowed on format.swf.utils.BitArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/utils/BitArray.hx:71: characters 4-8 : Array access is not allowed on format.swf.utils.BitArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/utils/BitArray.hx:75: characters 4-8 : Array access is not allowed on format.swf.utils.BitArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/SWFData.hx:310: characters 9-13 : Array access is not allowed on format.swf.SWFData
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/SWFData.hx:872: characters 17-21 : Array access is not allowed on format.swf.SWFData
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/SWFData.hx:919: characters 17-21 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/tags/TagDebugID.hx:43: characters 51-55 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/tags/TagDebugID.hx:44: characters 43-47 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/tags/TagDebugID.hx:45: characters 43-47 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/tags/TagDebugID.hx:46: characters 43-47 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/tags/TagDebugID.hx:47: characters 58-62 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/tags/TagDefineBitsJPEG4.hx:30: characters 6-16 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/tags/TagDefineBitsJPEG3.hx:30: characters 6-16 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/tags/TagDefineBitsJPEG2.hx:23: characters 6-16 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/data/etc/MPEGFrame.hx:146: characters 2-9 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/data/etc/MPEGFrame.hx:153: characters 2-6 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/tags/TagDefineSound.hx:128: characters 9-12 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/tags/TagDefineSound.hx:137: characters 9-12 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/tags/TagDefineSound.hx:146: characters 30-33 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/tags/TagDefineSound.hx:147: characters 30-33 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/tags/TagDefineSound.hx:148: characters 30-33 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/tags/TagDefineSound.hx:149: characters 30-33 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/tags/TagDefineSound.hx:151: characters 28-31 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/haxe/lib/swf/1,7,6/format/swf/tags/TagDefineSound.hx:152: characters 28-31 : Array access is not allowed on flash.utils.ByteArray

**Comment by jgranick** [comment]
Hi!

Are you forcing type "swf" at all? It looks sort of like it's trying to use type "swf" instead of "swflite" on HTML5, which does not work. You need to use `<library path="to/your.swf" />` (and don't specify the type) or `<library path="to/your.swf" type="swflite" />` to allow it to use SWFLite for the HTML5 target

**Comment by redannick** [comment]
Thanks for getting back to me Joshua, I wasn't specifying the type. I've tried forcing swflite and that yields the same errors. This is my library line:
<library path="lib/myswf.swf" id="myswf" preload="true" generate="true" />

**Comment by jgranick** [comment]
Do you get the same error when you try using "SimpleSWFLayout" or "NyanCat" from OpenFL samples? (openfl create SimpleSWFLayout, etc)

**Comment by redannick** [comment]
With both of those I get:
Export/html5/haxe/DefaultAssetLibrary.hx:714: character 9 : Invalid escape sequence
on publish. Perhaps I have some weird versions going on?

Windows 8.1:

$ haxelib list
actuate: [1.8.1]
as3hx: [1.0.2]
hxcpp: [3.1.68]
layout: [1.1.0]
lime: [2.0.6]
minject: [1.6.0]
mmvc: [1.6.0]
msignal: [1.2.2]
openfl-html5-dom: [1.2.2]
openfl-samples: [2.2.1]
openfl: [2.2.4]
swf: 1.7.5 [1.7.6]

I'm not sure why my swf is listing 1.7.5 as well as 1.7.6 for example.

**Comment by jgranick** [comment]
Can you look up that file, and see what's printed on line 714? Thanks :smile:

**Comment by redannick** [comment]
```@:file("...path...\SimpleSWFLayout\Export\html5/obj/libraries/layout/layout.dat") class __ASSET__libraries_layout_layout_dat extends lime.utils.ByteArray {}```

**Comment by jgranick** [comment]
That looks weird :smile:

The similar line on my system looks like:

`@:file("/Users/joshua/Projects/Samples/SimpleSWFLayout/Export/html5/obj/libraries/layout/layout.dat") class __ASSET__libraries_layout_layout_dat extends lime.utils.ByteArray {}`

It looks like it's having trouble creating the absolute path. Could you build using `-verbose` and see if it prints any funny paths out anywhere? Are you running `openfl test html5` from the same directory, in a command-prompt, or are you using it in a different way? :confused:

**Comment by redannick** [comment]
ah the ...path... was me protecting my clients name, sorry

**Comment by redannick** [comment]
I added -verbose and SimpleSWFLayout compiled and ran. Then I switched to NyanCat and *didn't* add verbose and that worked too. My original project still gives the same errors and offers no extra output with -verbose though :(

**Comment by jgranick** [comment]
Ah, okay :smile:

Oh, so it is working. Interesting, that's a good sign, and it wasn't before?

I'm trying to think what I can do, what if you try using a very simple project (such as NyanCat) and using your SWF instead? Does that work?

**Comment by redannick** [comment]
ok so that came up with the "invalid escape sequence" error again, so I added -verbose again, and then it compiled fine. I put an asset on the stage now! woohoo, albeit way too big and no text. So I guess it must be something up with the rest of my project.

**Comment by redannick** [comment]
What content is supported from swf files in html5? I can see some simple MovieClips with shapes, but no SimpleButtons, and no text. Is that to be expected?

**Comment by jgranick** [comment]
I thought SimpleButton was supported, but perhaps not yet. The text should require you to embed the same font separately -- otherwise, we cannot generate all the webfonts required for accurately reproducing it :smile:

**Comment by redannick** [comment]
ok thanks, I should be able to convert those to MovieClips easily enough. I think I have this working now in my original project, but I've stopped using generate="true" I suspect this is what was causing those errors...

Thanks for your help Joshua - first class support as always! :)

**Comment by T1mL3arn** [comment]
I got the similar errors right now for html5
```XML
<haxelib name="swf" />

<library path="assets/testLib.swf" preload="true" />
```
```Haxe
var mc = Assets.getMovieClip("testLib:Barrel1");
mc.x = mc.y = 200;
addChild(mc);
```
Haxe 3.2.0-rc2, OpenFl 3.0.3 , Lime 2.3.3

Full error log
```
C:/HaxeToolkit/swf/1,8,6/format/swf/utils/BitArray.hx:20: characters 18-22 : Array access is not allowed on format.swf.utils.BitArray
C:/HaxeToolkit/swf/1,8,6/format/swf/utils/BitArray.hx:67: characters 4-8 : Array access is not allowed on format.swf.utils.BitArray
C:/HaxeToolkit/swf/1,8,6/format/swf/utils/BitArray.hx:71: characters 4-8 : Array access is not allowed on format.swf.utils.BitArray
C:/HaxeToolkit/swf/1,8,6/format/swf/utils/BitArray.hx:75: characters 4-8 : Array access is not allowed on format.swf.utils.BitArray
C:/HaxeToolkit/swf/1,8,6/format/swf/SWFData.hx:310: characters 9-13 : Array access is not allowed on format.swf.SWFData
C:/HaxeToolkit/swf/1,8,6/format/swf/tags/TagDebugID.hx:43: characters 51-55 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/tags/TagDebugID.hx:44: characters 43-47 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/tags/TagDebugID.hx:45: characters 43-47 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/tags/TagDebugID.hx:46: characters 43-47 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/tags/TagDebugID.hx:47: characters 58-62 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/tags/TagDefineBitsJPEG4.hx:30: characters 6-16 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/tags/TagDefineBitsJPEG3.hx:30: characters 6-16 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/tags/TagDefineBitsJPEG2.hx:23: characters 6-16 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/data/etc/MPEGFrame.hx:146: characters 2-9 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/data/etc/MPEGFrame.hx:153: characters 2-6 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/tags/TagDefineSound.hx:128: characters 9-12 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/tags/TagDefineSound.hx:137: characters 9-12 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/tags/TagDefineSound.hx:146: characters 30-33 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/tags/TagDefineSound.hx:147: characters 30-33 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/tags/TagDefineSound.hx:148: characters 30-33 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/tags/TagDefineSound.hx:149: characters 30-33 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/tags/TagDefineSound.hx:151: characters 28-31 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/tags/TagDefineSound.hx:152: characters 28-31 : Array access is not allowed on flash.utils.ByteArray
C:/HaxeToolkit/swf/1,8,6/format/swf/SWFData.hx:872: characters 17-21 : Array access is not allowed on format.swf.SWFData
C:/HaxeToolkit/swf/1,8,6/format/swf/SWFData.hx:919: characters 17-21 : Array access is not allowed on flash.utils.ByteArray
```

**Comment by T1mL3arn** [comment]
Oh, the problem was here - ```import format.SWF;``` .  This import was used for flash compilation for this:
```Haxe
 var swf = new SWF(Assets.getBytes("assets/testLib.swf"));
```
Without import compilation to html5 works fine.
