### ISSUE TITLE
Error with reading 8Bit bitmap from swf...

### ISSUE THREAD

**Issue by osoker** [openfl/swf#42]
The following code in package format.swf.instance.Bitmap 
					var imageData = new ByteArray ();
					var padding = Math.ceil (data.bitmapWidth / 4) - Math.floor (data.bitmapWidth / 4);

should be replaced by:
	var imageData = new ByteArray ();
        var padding = Math.ceil (data.bitmapWidth / 4.0)*4 - data.bitmapWidth;

or some other code can align four bytes in one bitmap scanline.

**Comment by pythonmax** [comment]
I agree that padding calculation formula is wrong.

Consider the following test:
```
class Main {
    static public function main() {
        test(getPadding);
        test(getPaddingFixed);
    }

    private static function test(fn:Int -> Int) {
        try {
            assertEquals(0, fn(40));
            assertEquals(3, fn(41));
            assertEquals(2, fn(42));
            assertEquals(1, fn(43));
            assertEquals(0, fn(44));
            trace('PASSED');
        } catch (error:String) {
            trace('FAILED: $error');
        }
    }

    private static function getPadding(width:Int):Int {
        return Math.ceil (width / 4) - Math.floor (width / 4);
    }

    private static function getPaddingFixed(width:Int):Int {
        return (4 - width % 4) % 4;
    }

    private static function assertEquals(expected:Int, actual:Int){
        if (expected != actual) {
            throw 'Expected $expected but was $actual';
        }
    }

}
```

Run it with `haxe -main Main --interp`.
The formula taken from Bitmap.hx fails to calculate correct padding for any width except those when no padding is needed (width % 4 == 0).
I suggest using `(4 - width % 4) % 4` or similar.

**Comment by pythonmax** [comment]
I looked for usages of field bitmapWidth and found that as far as I can tell format.swf.exporters.SWFLiteExporter do not take into account any padding at all in case of 8-bit png.
Am I wrong?
