### ISSUE TITLE
Code error with reading 8Bit palette bitmap data

### ISSUE THREAD

**Issue by osoker** [openfl/swf#43]
The following code in package format.swf.instance.Bitmap ：
				if (data.bitmapFormat == BitmapFormat.BIT_8) {
					
					var colorTable = new Array <Int> ();
					
					for (i in 0...data.bitmapColorTableSize) {

data.bitmapColorTableSize can express max data with 255, But  palette data size maybe with max datasize 256, So i guess here should be ：
					for (i in 0...(data.bitmapColorTableSize + 1) ) {

I use this  +1 code with as3 , It's correct with my image

**Comment by pythonmax** [comment]
I confirm this issue.
The fix should be in format.swf.tags.TagDefineBitsLossless.hx:
In function parse:
```
bitmapColorTableSize = data.readUI8(); + 1;
```
In function publish:
```
body.writeUI8(bitmapColorTableSize - 1);
```
