### ISSUE TITLE
error while compiling for flash

### ISSUE THREAD

**Issue by boorik** [openfl/swf#45]
Hi, I get an error while compiling for flash target using v2.0.1 :

D:/Dev/HaxeToolkit/haxe/lib/swf/2,0,1/format/swf/instance/Bitmap.hx:124: characters 4-20 : flash.display.BitmapData has no field image
D:/Dev/HaxeToolkit/haxe/lib/swf/2,0,1/format/swf/instance/Bitmap.hx:126: characters 4-20 : flash.display.BitmapData has no field image
D:/Dev/HaxeToolkit/haxe/lib/swf/2,0,1/format/swf/instance/Bitmap.hx:127: characters 4-20 : flash.display.BitmapData has no field image

**Comment by boorik** [comment]
I use the "openfl-legacy" flag

**Comment by jgranick** [comment]
Does it work if you remove the "openfl-legacy" flag on the Flash target? There is no legacy Flash target :wink:

**Comment by jgranick** [comment]
It's actually strange that this file is even showing up for the Flash target. Is there some sample project I could use to recreate this? Do you have trouble using "SimpleSWFLayout", "NyanCat" or another sample with SWF assets?

**Comment by boorik** [comment]
I am able to reproduce it with NyanCat sample.
Just add "<set name="openfl-legacy" unless="web"/>" in the project file

I use haxeui lib and this flag is in his include.xml

**Comment by boorik** [comment]
sorry <set name=openfl-legacy unless=web/> didn't show in the previous message

**Comment by hopewise** [comment]
I can't compile my app to flash, I still get:
    Error:(124, 4) flash.display.BitmapData has no field image

What to do?
I have swf 2.0.3, openfl 3.3.5

**Comment by boorik** [comment]
I have done a fix for this issue on a fork : 450c9c41ccd4302809dfb8b502f3eaf170dd224f

**Comment by hopewise** [comment]
Thanks, it worked, I also opened an issue here: https://github.com/openfl/swf/issues/49
