### ISSUE TITLE
Inconsistent exported 8 bit PNGs

### ISSUE THREAD

**Issue by andresa88** [openfl/swf#54]
So there are two issues here. The first 2 images are the original 8 bit png images and the last 2 are the images extracted from the swf when targeting HTML5.

1. The first exported image (150x150) comes out distorted when processed by the SWF library. The 2nd exported image (200x200) exhibits no distortion , so it seems to only happen for images below a certain size.
2. Alpha transparency does not work, any transparent pixels come out black as seen in the 2nd exported image with the hole in the center.

![i-8bit-150x150](https://cloud.githubusercontent.com/assets/7615261/11322175/ba77c61a-9093-11e5-81d9-95495b897828.png)
![i-8bit-200x200](https://cloud.githubusercontent.com/assets/7615261/11322172/ba77b440-9093-11e5-88bd-f6209489ea3f.png)
![swf-8bit-150x150](https://cloud.githubusercontent.com/assets/7615261/11322173/ba77e438-9093-11e5-8d6d-64764074a9a1.png)
![swf-8bit-200x200](https://cloud.githubusercontent.com/assets/7615261/11322174/ba7804ea-9093-11e5-86fb-ecb1d6ccdc4d.png)

**Comment by andresa88** [comment]
So for the 1st issue, I was playing around with the format.swf.exporters.SWFLiteExporter class and found that if I add a 2 to this line in the addBitmap() method.

buffer.position += data.bitmapWidth

becomes:

buffer.position += data.bitmapWidth + 2;

The exported PNG comes out fine.

**Comment by jgranick** [comment]
Perhaps the stride is byte-aligned, meaning it will need +0, +1, +2 or +3 depending on the width (potentially)

If the FLA is using JPEG compression then it will not use alpha in the image, but will export separately, or this is definitely PNG? Can you tell if the `transparent` value is true?

**Comment by andresa88** [comment]
The compression setting in the FLA for both images is set to Lossless (PNG/GIF) so this is only for PNGs.

And yes, transparent is true for both images.

**Comment by andresa88** [comment]
Never thought I'd be able to figure this out since I've never dealt with encodings and byte structures, but here I am. I searched for the SWF specs and it was a surprisingly simple to figure out wow. Of course, most of the hard work was already done before me, but it was just missing the logic to round off the byte row count to the nearest 32-bit word. So I'll commit the fix soon.

So I'll give the 2nd issue a shot now that I'm figuring this stuff out.

**Comment by andresa88** [comment]
And fixed the 2nd issue.
