### ISSUE TITLE
Weird bug with Font embedding

### ISSUE THREAD

**Issue by loudoweb** [openfl/swf#56]
1. Create a dynamic textfield named **txt_1** with random characters on Flash CC (+OpenFL plugin) using this font (Helvetica Neue LT Std 67 Medium Condensed) http://font2s.com/fonts/50722/helvetica_neue_lt_std_67_medium_condensed.html#.VlsK-zJMI2F

2. Compile your haxe/OpenFL project to display the MovieClip that contains the dynamic textfield.

**RESULTS** :
A. On HTML5 it's ok, but **on flash the font displayed is wrong** (probably times new roman) and if you trace the embedFonts property it's false (but true on html5).
```haxe
txt = cast col.getChildByName('txt_1');
trace(txt.embedFonts); // false on flash (and incorrect font displayed), true on html5
```
B. If you force the **embedFonts property to true with haxe, all characters disappear**!
```haxe
txt = cast col.getChildByName('txt_1');
txt.embedFonts = true;//the random text set in Flash CC disappear
```
C: If you **create a textfield direcly from haxe with the same TextFormat in the same MovieClip, everything is OK**! Strange...
```haxe
var format:TextFormat = txt.defaultTextFormat;//get the same textFormat !!
txt = new TextField();
txt.defaultTextFormat = format;
txt.embedFonts = true;
txt.text = "Lorem ipsum dolor amet";
txt.width = 300;
txt.height = 50;
addChild(txt);//everything is ok
```
Do you know where the problem comes from and how this can be fixed? Without any fix it's useless to use Flash CC. Do you have similar problems with others fonts?

Also, why the font rendering is forced to **"Device Fonts"** in Flash CC/OpenFL plugin? It seems that when I import a textfield with another font rendering from another flash CC project, the font will be correct in the final swf but the textfield will only use the random characters set in the Flash CC textfield.

I'm not even sure the problem comes from this library but any help appreciated.

**Comment by robgraeber** [comment]
+1

**Comment by robgraeber** [comment]
@loudoweb were you able to figure this out?

**Comment by loudoweb** [comment]
@robgraeber Not really. I'm still using a fix for flash target that removes the buggy textfield and replace it with a new one with same properties. https://gist.github.com/loudoweb/8229711420c7a1bd0e72

**Comment by jgranick** [comment]
The plugin uses SWFLite output by default, which does not embed fonts. You need to embed the fonts on your own. This is why `embedFonts` results in blank output in Flash, and why the text displays with a different font in HTML5. The font you use should be embedded in project.xml :smile:

**Comment by loudoweb** [comment]
Hello, I had this in my project.xml

```
<assets path="Assets/fonts" rename="fonts" include="*.otf" if="flash" />
<assets path="Assets/fonts" rename="fonts" if="html5" />
```

In the description of the problem above (please see **C.**), I can have in flash the correct font if I create the Textfield instance in Haxe with `embedFonts=true`. So the font is embedded. But there is a bug somewhere that prevent correct font embedding from SWFLite. Also, I've check in the export swf if the font is embedded (I can see that in FlashDevelop) and I can confirm the font is embedded (but strange, the last character of the font name is missing, but it doesn't explain why it works when creating a textfield by code anyway...I've got `Helvetica Neue LT Std 75 Bold (Bold 74)` in Animate swf and `Helvetica Neue LT Std 75 Bol (Bold 252)` (without the d of bold) in export swf)

I will pursue this project in late August or September I think, so I will see if the bug still occurs and try to give more information. Maybe the best thing I can do is to make a sample project.
