### ISSUE TITLE
error while processing swf file 

### ISSUE THREAD

**Issue by zengjie** [openfl/swf#57]
After updating swf lib to **2.1.4**, following error occurred.

```Error: End of file was encountered```

I have tried these targets: html5, cpp and flash. The results are the same.
When set swf to 2.1.3, everything is okay.

Haxe: 3.2.1
Lime: 2.8.0
OpenFL: 3.5.0
OS: Mac OS X 10.11.1 

The swf file being processed:
[library.swf.zip](https://github.com/openfl/swf/files/56293/library.swf.zip)

**Comment by ivanangonoa123** [comment]
Hahahaha having this issue right now! live!

**Comment by jgranick** [comment]
This is fixed now, will go out soon :smile: :shipit:
