### ISSUE TITLE
adding "id" tag to "library" for swf breaks HTML5 target

### ISSUE THREAD

**Issue by rickthepick** [openfl/swf#59]
openfl 3,4,0
swf 2,1,3

    <library path="Assets/loading_screen.swf" preload="true" id="everything" />
    clip = Assets.getMovieClip("everything:");

That works fine in Flash and Mac OS targets of openfl, but gives "There is no asset library named "everything"" in the browser console for the HTML5 target.  This problem doesn't happen with my other swfs.  Looks like everything generated properly, e.g., I see "Export/html5/obj/libraries/everything/everything.dat".

workaround:

    <library path="Assets/loading_screen.swf" preload="true" />
    clip = Assets.getMovieClip("loading_screen:");

I suspect this is some kind of race condition.  I moved the "library" element from last in the list to first and it started working.
Also in the browser console I see:
    Assets.hx:235: [openfl.Assets] There is no asset library named "everything" SimpleS...yout.js (line 5622)
    Assets.hx:235: [openfl.Assets] There is no asset library named "everything" SimpleS...yout.js (line 5622)
    Assets.hx:235: [openfl.Assets] There is no asset library named "everything" SimpleS...yout.js (line 5622)
   DynamicTextField.hx:91: Warning: Could not find required font "Impact", it has not been embedded

No idea why it is loading the app four times, but it worked the fourth time.  It's just a simple "hello world" type app:

    class Main extends Sprite {
      private var clip:MovieClip;
      public function new() {
        super();
        clip = Assets.getMovieClip("everything:");
        addChild(clip);

**Comment by jgranick** [comment]
This appears to be fixed, thank you! :smile:
