### ISSUE TITLE
Swf InputTextFields not working

### ISSUE THREAD

**Issue by KnightMearh** [openfl/swf#61]
When loading a swf into openfl, all input text fields are being created as type DynamicTextField and don't accept input.

If I use InputTextField in openfl directly (making my own), the input works fine for them.

openfl 3.5.3
swf 2.1.6

**Comment by jgranick** [comment]
In the latest development version of OpenFL, we have merged the SWF functionality into the core of OpenFL. This issue is now fixed, thank you :smile:
