### ISSUE TITLE
Text field border option fill not working

### ISSUE THREAD

**Issue by KnightMearh** [openfl/swf#62]
When using "show border around text" option in Adobe Flash, it renders the text field with a black border and white background fill.

However, when you load that swf in openfl, it only renders the black border (no bg fill). Not sure if this is intentional as the option does seem to indicate it should only effect the border, however I'd be inclined to mimic whatever Flash does for consistency. ie, set that text fields border = true and borderColor = 0xFFFFFF.

**Comment by jgranick** [comment]
Fixed, thank you :smile:
