### ISSUE TITLE
missing FrameObject data on MovieClip with more than 1 frame

### ISSUE THREAD

**Issue by loudoweb** [openfl/swf#81]
Target : html5
tool used : AnimateCC

1. Make a MovieClip with 2 key frames. 
2. Draw a red shape on first frame.
3. Draw a black shape on the 2nd frame.

**EDIT** : using bitmap instead of shape has the same behavior

Then in your code, try a gotoAndStop(2);
It will render the first frame (red shape) !

This has already been reported [here ](http://community.openfl.org/t/how-to-use-swflite/7498/6?u=loudo) and [here](http://community.openfl.org/t/feedback-creating-a-flash-html5-app-with-flashcc-openfl/7385).

I have made some research and it seems that on frame 2, there is no object, it's empty, so the renderFrame method can't draw anything except frame 1 for some reason.
 
in _MovieClip.__renderFrame()_
_format.swf.lite.MovieClip.__symbol.frames[1].objects_ **is empty** ! **It should contain a FrameObject**.

So it's not really an issue on the __renderFrame method, but it's an issue on how objects are populated in each frame.

I would like to help but I don't know where the objects are populated (macro?) @jgranick

**Comment by loudoweb** [comment]
I'm currently investigating on SWFLiteExporter.

SWFLiteExporter.hx:463 : should trace {label name of current object, FrameData}
SWFLiteExporter.hx:485 : should trace {error?} each time `continue` is executed [here](https://github.com/openfl/swf/blob/596c5eec79506fa21ccbfa5f7a509afc030cbc52/format/swf/exporters/SWFLiteExporter.hx#L485).

Here are my results with a MovieClip of 10 frames/2 labeled key frames.

```
SWFLiteExporter.hx:463: bleu,  Depth: 1, CharacterId: 1, PlacedAt: 1, IsKeyframe
SWFLiteExporter.hx:463: null,  Depth: 1, CharacterId: 1, PlacedAt: 1
SWFLiteExporter.hx:485: error?
SWFLiteExporter.hx:463: null,  Depth: 1, CharacterId: 1, PlacedAt: 1
SWFLiteExporter.hx:485: error?
SWFLiteExporter.hx:463: null,  Depth: 1, CharacterId: 1, PlacedAt: 1
SWFLiteExporter.hx:485: error?
SWFLiteExporter.hx:463: null,  Depth: 1, CharacterId: 1, PlacedAt: 1
SWFLiteExporter.hx:485: error?
SWFLiteExporter.hx:463: jaune,  Depth: 1, CharacterId: 2, PlacedAt: 1, IsKeyframe
**SWFLiteExporter.hx:485: error?**
SWFLiteExporter.hx:463: null,  Depth: 1, CharacterId: 2, PlacedAt: 1
SWFLiteExporter.hx:485: error?
SWFLiteExporter.hx:463: null,  Depth: 1, CharacterId: 2, PlacedAt: 1
SWFLiteExporter.hx:485: error?
SWFLiteExporter.hx:463: null,  Depth: 1, CharacterId: 2, PlacedAt: 1
SWFLiteExporter.hx:485: error?
SWFLiteExporter.hx:463: null,  Depth: 1, CharacterId: 2, PlacedAt: 1
SWFLiteExporter.hx:485: error?
```

Lines in bold should not be there because we need to instanciate a FrameObject.

**Comment by loudoweb** [comment]
So the reason why the object is not instanciated is because the 2 key frames share the same placeAtIndex (see the if operator [here](https://github.com/openfl/swf/blob/596c5eec79506fa21ccbfa5f7a509afc030cbc52/format/swf/exporters/SWFLiteExporter.hx#L473))

**Comment by jgranick** [comment]
The SWFLite exporter attempts to detect frames that are identical, so we don't 1000-length arrays of repeated data :wink:

Perhaps it needs to check the placedAtIndex as well as the CharacterId to detect if there was a change

**Comment by loudoweb** [comment]
What does placeAtIndex stores exactly ? Should the data be different for the different object?

**Comment by jgranick** [comment]
Oh, you know what -- I think that `placedAtIndex` is always a unique number for each unique object (I believe) but I think index 1 might be a special index that basically means that this is really drawn to the parent `graphics` object, so `sprite.graphics`, not `sprite.addChild (shape)` with graphics

Anyway, the key is the character ID changes, which means we need a redraw with new graphic instructions

**Comment by loudoweb** [comment]
>  index 1 might be a special index that basically means that this is really drawn to the parent graphics object, so sprite.graphics, not sprite.addChild (shape) with graphics

I've swapped shapes by bitmaps and I still have placedAtIndex = 1 in my results.

**Comment by loudoweb** [comment]
Well, it's seems a regression bug since commit https://github.com/openfl/swf/commit/00d0891deb4e9c4e4091cdcc88b19b4b429d7d7f#diff-350f894bda0f84d00520d11fb5ca15c8 by @raggy 

Switching back to the old code of Frame.hx fixes the bug.

So 

```
frameObject.lastModifiedAtIndex = 0;
frameObject.placedAtIndex = tagIndex;
```

instead of 

```
if(tag.hasName || tag.hasMatrix || tag.hasColorTransform || tag.hasFilterList) {
					frameObject.lastModifiedAtIndex = tagIndex;
}
```

**Comment by T1mL3arn** [comment]
Just wanted to create issue right now,  but it does already exist. @loudoweb thanks for fix!
